# version: '3.7'

# services:

#   web:
#     build: GuardianClient
#     image: theguardianclient:v1.2
#     ports:
#       - 4200:80
#     networks:
#       - default


# networks:
#   default:

version: '3.7'

services:

  example:
    container_name: example
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'