apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-front
  labels:
    app: guardian
    role: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardian
      role: front
  template:
    metadata:
      labels:
        app: guardian
        role: front
    spec:
      containers:
      - name: guardian-front
        image: anvelez26/theguardianclient:1.2
        ports:
        - containerPort: 80