apiVersion: v1
kind: Service
metadata:
  name: guardian-front
  labels:
    app: guardian
    role: front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guardian
    role: front